version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: kulanit63070011/my-backend_image:1.0
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: kulanit63070011/my-frontend_image:1.0
